project:
  type: website

website:
  title: "Luke Ashton"
  site-url: https://luke-ashton.netlify.app
  description: "This is Luke Ashton's personal blog."
  navbar:
    left: 
      - text: Blog
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/Luke-Ashton
      - icon: google
        href: https://scholar.google.com/citations?user=2kSpXFEAAAAJ&hl=en
      - icon: strava
        href: https://www.strava.com/athletes/31921497
      - icon: rss
        href: blog.xml
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
comments: 
  giscus: 
    repo: Luke-Ashton/blog

editor: visual

