project:
  type: website

website:
  title: "Musings of a PhD Student"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Luke-Ashton
      - icon: google
        href: https://scholar.google.com/citations?user=2kSpXFEAAAAJ&hl=en
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

